CREATE TABLE brand(ID INTEGER PRIMARY KEY);
CREATE TABLE product(ID INTEGER PRIMARY KEY);
CREATE TABLE product_price(
	BRAND_ID INTEGER,
	CURR VARCHAR(3),
	END_DATE TIMESTAMP,
	PRICE_LIST INTEGER PRIMARY KEY,
	PRICE DECIMAL(8, 2),
	PRIORITY INTEGER,
	PRODUCT_ID INTEGER,
	START_DATE TIMESTAMP
);