CREATE TABLE brand(ID INTEGER PRIMARY KEY);
CREATE TABLE product(ID INTEGER PRIMARY KEY);
CREATE TABLE product_price(
	BRAND_ID INTEGER,
	CURR VARCHAR(3),
	END_DATE TIMESTAMP,
	PRICE_LIST INTEGER PRIMARY KEY,
	PRICE DECIMAL(8, 2),
	PRIORITY INTEGER,
	PRODUCT_ID INTEGER,
	START_DATE TIMESTAMP,
	CONSTRAINT fk_price_list_to_brand FOREIGN KEY (BRAND_ID) REFERENCES brand(id),
	CONSTRAINT fk_price_list_to_product FOREIGN KEY (PRODUCT_ID) REFERENCES product(id)
);